export default {
  "login": "Sudip777",
  "id": 83223293,
  "node_id": "MDQ6VXNlcjgzMjIzMjkz",
  "avatar_url": "https://avatars.githubusercontent.com/u/83223293?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/Sudip777",
  "html_url": "https://github.com/Sudip777",
  "followers_url": "https://api.github.com/users/Sudip777/followers",
  "following_url": "https://api.github.com/users/Sudip777/following{/other_user}",
  "gists_url": "https://api.github.com/users/Sudip777/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/Sudip777/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/Sudip777/subscriptions",
  "organizations_url": "https://api.github.com/users/Sudip777/orgs",
  "repos_url": "https://api.github.com/users/Sudip777/repos",
  "events_url": "https://api.github.com/users/Sudip777/events{/privacy}",
  "received_events_url": "https://api.github.com/users/Sudip777/received_events",
  "type": "User",
  "site_admin": false,
  "name": "Sudip Parajuli",
  "company": "xyz",
  "blog": "https://sudipparajuli.com.np",
  "location": "Nepal",
  "email": null,
  "hireable": null,
  "bio": " Aspiring Programmer | Tech Enthusiast | \r\nGetting 1% better every day⏳",
  "twitter_username": "sudipparajuli10",
  "public_repos": 16,
  "public_gists": 0,
  "followers": 2,
  "following": 3,
  "created_at": "2021-04-26T12:42:30Z",
  "updated_at": "2023-05-24T09:58:07Z"
}